project:
  type: website
  output-dir: docs

website:
  title: "Worms Blog"
  site-url: https://marcoworms.github.io/blog/
  site-path: /blog/
  navbar:
    right:
      - icon: twitter
        href: https://twitter.com/MarcoWorms
      - icon: github
        href: https://github.com/MarcoWorms
format:
  html:
    # theme: default
    # theme: cerulean
    # theme: cosmo
    # theme: cyborg
    # theme: darkly
    # theme: flatly
    # theme: journal
    # theme: litera
    # theme: lumen
    # theme: lux
    # theme: materia
    # theme: minty
    # theme: morph
    # theme: pulse
    # theme: quartz
    # theme: sandstone
    # theme: simplex
    # theme: sketchy
    # theme: slate
    # theme: solar
    theme: spacelab
    # theme: superhero
    # theme: united
    # theme: vapor
    # theme: yeti
    # theme: zephyr
    css: styles.css
